name: Generate static site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync To CloudFlare
        uses: michaelliao/sync-s3-compatible-action@v5
        env:
          SYNC_DIR: site
          SYNC_OPT_UNUSED: delete
          SYNC_TYPE: cloudflare
          SYNC_REGION: ${{ secrets.REGION }}
          SYNC_BUCKET: ${{ secrets.BUCKET }}
          SYNC_ACCESS_ID: ${{ secrets.ACCESS_KEY_ID }}
          SYNC_ACCESS_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}

      - name: Generate Index
        uses: michaelliao/build-index-action@v1
        env:
          SYNC_REGION: ${{ secrets.REGION }}
          SYNC_BUCKET: ${{ secrets.BUCKET }}
          SYNC_ACCESS_ID: ${{ secrets.ACCESS_KEY_ID }}
          SYNC_ACCESS_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
